In [3]:
import torch
import numpy as np

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data, x_data.dtype

(tensor([[1, 2],
         [3, 4]]),
 torch.int64)

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np, x_np.dtype

(tensor([[1, 2],
         [3, 4]], dtype=torch.int32),
 torch.int32)

In [8]:
torch.tensor(np_array)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
x_ones = torch.ones_like(x_data)

In [10]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [11]:
x_ones.dtype

torch.int64

In [12]:
np_array.dtype

dtype('int32')

In [16]:
x_rand = torch.rand_like(x_data, dtype=torch.float64)
x_rand, x_rand.dtype

(tensor([[0.5952, 0.3627],
         [0.3072, 0.1978]], dtype=torch.float64),
 torch.float64)

In [20]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.4661, 0.8663, 0.8827],
         [0.4691, 0.5245, 0.6850]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [26]:
ones_tensor.dtype

torch.float32

In [27]:
torch.tensor([1, 2, 3]).dtype

torch.int64

In [28]:
tensor = torch.rand(3, 4)

In [29]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [30]:
tensor

tensor([[0.5712, 0.9660, 0.0942, 0.8492],
        [0.7082, 0.2157, 0.9383, 0.5686],
        [0.3730, 0.7944, 0.0259, 0.9701]])

In [31]:
tensor = tensor.to("cuda")

In [32]:
tensor.device

device(type='cuda', index=0)

In [33]:
x = torch.rand_like(tensor)
x.shape, x.dtype, x.device

(torch.Size([3, 4]), torch.float32, device(type='cuda', index=0))

In [34]:
tensor = torch.ones(4,4)

In [35]:
tensor[0], tensor[:, 0], tensor[..., -1]

(tensor([1., 1., 1., 1.]), tensor([1., 1., 1., 1.]), tensor([1., 1., 1., 1.]))

In [36]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
sum = tensor.sum()

In [39]:
sum

tensor(16.)

In [40]:
sum.shape, sum.dtype, sum.device

(torch.Size([]), torch.float32, device(type='cpu'))

In [44]:
type(sum.item())

float

In [49]:
tensor = torch.ones(4, 4)
tensor_copy = tensor
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)
print(tensor_copy)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [50]:
tensor = torch.ones(4, 4)
tensor_copy = tensor
print(f"{tensor} \n")
tensor += 5
print(tensor)
print(tensor_copy)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [51]:
tensor = torch.ones(4, 4)
tensor_copy = tensor
print(f"{tensor} \n")
tensor = tensor + 5
print(tensor)
print(tensor_copy)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [53]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [54]:
t += 1
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [55]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [60]:
n = np.ones(5)
t = torch.from_numpy(n)
t2 = torch.tensor(n)

print(f"n : {n}")
print(f"t: {t}")
print(f"t2: {t2}")

n += 1

print(f"n : {n}")
print(f"t: {t}")
print(f"t2: {t2}")

n : [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
t2: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
t2: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [62]:
torch.tensor([1,2,3]).dtype, np.array([1, 2, 3]).dtype

(torch.int64, dtype('int32'))